### ISSUE TITLE
Animations override opacity settings

### ISSUE THREAD

**Issue by Kaze919** [daneden/animate.css#386]
Hey I apologize if this is an easy one but I setup a fadeIn animation on my top navigation bar and it works fine except I lost the ability to have it be semi-transparent. Is there any way to override this or am I stuck with one or the other.

**Comment by Sundypha** [comment]
As you can see in the CSS file, the fadeIn is simple to edit

```CSS
@-webkit-keyframes fadeIn {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}

@keyframes fadeIn {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}

.fadeIn {
  -webkit-animation-name: fadeIn;
  animation-name: fadeIn;
}
````

better would be another animation for your needs, e.g. for 50% transparency:

```CSS
@-webkit-keyframes fadeInNavigation {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 0.5;
  }
}

@keyframes fadeInNavigation {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 0.5;
  }
}

.fadeIn {
  -webkit-animation-name: fadeInNavigation;
  animation-name: fadeInNavigation;
}
````

now you could add fadeInNavigaion as your desired animation
