### ISSUE TITLE
Infinite rotation without fading effect?

### ISSUE THREAD

**Issue by pepperstreet** [daneden/animate.css#436]
Hello, Animate.css looks awesome. But I am missing a very simple animation: Rotate. Maybe I am missing the obvious, but there is always a fade-in/out effect. No plain rotation preset.

**Question:**
How to get a simple rotation effect, left or right. Without fading.

Any clue? Thanks in advance.

**Comment by daneden** [comment]
This isn’t something I’m likely to add to Animate.css, but it’s a really simple animation you can do yourself:

```css
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.element {
  animation: spin 1s infinite linear;
}
```
