### ISSUE TITLE
bounceInLeft is not working on ios 9 safari browser

### ISSUE THREAD

**Issue by buriwoy** [daneden/animate.css#479]
but bounceOutLeft is working.

thanks for awesome lib :)

**Comment by klopfdreh** [comment]
Hi,

try this:

```css
@keyframes bounceInLeft {
  from, 60%, 30%, 75%, 90%, to {
    animation-timing-function: cubic-bezier(0.215, 0.610, 0.355, 1.000);
  }

  0% {
    opacity: 0;
    transform: translate3d(-3000px, 0, 0);
  }
  
  30% {
    opacity: 0;
    transform: translate3d(-1000px, 0, 0);
  }
  
  60% {
    opacity: 1;
    transform: translate3d(25px, 0, 0);
  }

  75% {
    transform: translate3d(-10px, 0, 0);
  }

  90% {
    transform: translate3d(5px, 0, 0);
  }

  to {
    transform: none;
  }
}

.bounceInLeft {
  animation-name: bounceInLeft;
}
```

Add the 30% keyframe to the set of frames.
