### ISSUE TITLE
How to replicate the random text color generator used in this website?

### ISSUE THREAD

**Issue by abyabrkal** [daneden/animate.css#640]
_animate.css_ website displays the Sample text (**Animate.css**) in randomly changing hue color.
How to replicate such a cool effect?

Anyone help me or point me the direction?

**Comment by DracotMolver** [comment]
This is the css.
You have to use background-clip to clip the background with the text. (Be awere of prefix...I'm not sure if all of them are needed)
``` css
.some-class {
   font-size: 5em;
   color: #f35626; /* This is not needed because you are using -webkit-text-fill-color: transparent. but It can be usefull with the currentColor property */ 
   -webkit-background-clip: text;
   -moz-background-clip: text;
   -ms-background-clip: text;
    background-clip: text;
   -webkit-text-fill-color: transparent;
   -moz-text-fill-color: transparent;
   -ms-text-fill-color: transparent;
   text-fill-color: transparent;
   background-image: -webkit-linear-gradient(92deg, currentColor, #feab3a);
   background-image:  -moz-linear-gradient(92deg, currentColor, #feab3a);
   background-image:  -ms-linear-gradient(92deg, currentColor, #feab3a);
   background-image:  linear-gradient(92deg, currentColor, #feab3a);
   animation: hue 60s infinite linear
}
```

Then you have to use the hue-gradient filter. (Take a look here: [http://www.w3schools.com/cssref/css3_pr_filter.asp](url)

The animation code will be something like this:
```css
@-webkit-keyframes hue {
  0%{
    -webkit-filter: hue-rotate(0deg)
  }
  100%{
    -webkit-filter: hue-rotate(-360deg)
  }
}
@-moz-keyframes hue {
  0%{
    -moz-filter: hue-rotate(0deg)
  }
  100%{
    -moz-filter: hue-rotate(-360deg)
  }
}
@-ms-keyframes hue {
  0%{
    -ms-filter: hue-rotate(0deg)
  }
  100%{
    -ms-filter: hue-rotate(-360deg)
  }
}
@keyframes hue {
  0%{
    filter: hue-rotate(0deg)
  }
  100%{
    filter: hue-rotate(-360deg)
  }
}

```
