### ISSUE TITLE
Turn off animations for printing

### ISSUE THREAD

**Issue by gregskloot** [daneden/animate.css#821]
When a user tries to print out the page, any elements that they haven't scrolled past have not yet loaded/animated so they are hidden in the print view. 

Using CSS media queries for print, is there a way to show all elements that have the animation classes when the user is printing?

**Comment by eltonmesquita** [comment]
Just do something like:
```css
@media print {
  .animated {
    animation: none!important;
  }
}
```
As I don't know how you're hiding your elements, I can't say for sure that'll work, but the idea should the same.
