### ISSUE TITLE
v3.7.2 still does not make the toast go away witthout a CSS override

### ISSUE THREAD

**Issue by gauravshahhere** [daneden/animate.css#975]
I tried moving to v3.7.2 in order to fix toasts on chrome v74 + (on v76) for `prefers-reduced-motion` media feature . I went through the commit and had to tweak the animation-duration and transition-duration properties so that the animation effect that I was using on the toasts would actually work. Here is the snippet that I put in my scss file:
```scss
@media (print), (prefers-reduced-motion: reduce) {
  .animated {
    -webkit-animation-duration: 1s !important;
    animation-duration: 1s !important;
    -webkit-transition-duration: 1s !important;
    transition-duration: 1s !important;
  }
}
```

I was not able to see any of the animation effects without actually changing to these values. I know the goal of the media feature is to stop animation but it seemed unnatural to actually change these values to get the normal toast animations to work. Is this the recommended approach?
